### PR TITLE
Update Android Gradle plugin to 3.2.0

### PR DESCRIPTION
**Pull request by MrPickles**
This PR change the build files to work with the latest of the Gradle tools that came out with Android Studio 3.2

### CODE REVIEW

**Comment by ThomasHabets** [comment]
There appears to be a merge conflict with this pull request. Could you please fix?

**Comment by MrPickles** [comment]
Hmm strange. It shows no merge conflict from my perspective.

no merge conflict

**Comment by MrPickles** [comment]
Hmm strange. It looks like there's no merge conflicts from my perspective.
no merge conflict

**Comment by ThomasHabets** [comment]
Strange. I get "This branch cannot be rebased due to conflicts
Rebasing the commits of this branch on top of the base branch cannot be performed automatically due to conflicts encountered while reapplying the individual commits from the head branch".

I'm on the road but will take care of this in a few days.

**Comment by MrPickles** [comment]
Sure, no rush. Additionally, I think we should get me write access to this repo. I'll chat with you internally about this.

**Pull request merged**
