### PR TITLE
Issue VACCUM SQL directive to prevent the DB from keeping old Seeds.

### PR DESCRIPTION
**Pull request by pfedan**

### CODE REVIEW

**Comment by pfedan** [comment]
I signed it!

**Comment by pfedan** [comment]
I'd consider this also a security issue (and if not, at least a matter of 'tidiness') to securely delete the seeds, see also [the documentation of VACUUM](https://www.sqlite.org/lang_vacuum.html) (third bullet in the top list).

**Comment by ThomasHabets** [comment]
Is that semicolon needed? The other instances of `mDatabase.execSQL` don't end in semicolon.

**Comment by ThomasHabets** [comment]
I've filed this internally as b/129332125 because…

\--

FYI: The version in Google Play Store / Apple App store is not the same as this opensource version. They've diverged. This opensource version is also unlikely to end up in the app stores. This open source version doesn't get much love, but I'll accept well-written pull requests. But don't expect this feature to be implemented by Google.

**Comment by ThomasHabets** [comment]
(will merge this anyway after you confirm the semicolon thingy)

**Comment by ThomasHabets** [comment]
Either is good.  Thanks!

**Pull request merged**
